# Generated by Django 6.0.6 on 2026-06-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='english',
            new_name='IndustrialInstrumentation',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='maths',
            new_name='ProcessControl',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='tamil',
            new_name='Sensors',
        ),
    ]
