# Generated by Django 6.0.6 on 2026-06-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_student_roll_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
