# Generated by Django 6.0.6 on 2026-06-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='paid_fee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fee',
            name='total_fee',
            field=models.PositiveIntegerField(),
        ),
    ]
