# Generated by Django 6.0.6 on 2026-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_fee_paid_fee_alter_fee_total_fee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_student_fee'),
        ),
    ]
